### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by hli2020** [salman-h-khan/ZSD_Release#1]
Really cool work on zero-shot detection. Run a few experiments on the toy examples. I think the w2v choice for each cluster/class is also crucial. Maybe a dynamic representation of the cluster is more elegant. Any plan to release the training code? :)

**Comment by Bigwode** [comment]
@hli2020 I have seen a keras version of the Faster-RCNN model on github. This code also made some minor changes based on it. Maybe you can read the paper and find the difference.

**Comment by salman-h-khan** [comment]
We have released the training code for our latest PL-ZSD model. Check out the repo: https://github.com/salman-h-khan/PL-ZSD_Release
