### ISSUE TITLE
How to get Model/config.pickle file?

### ISSUE THREAD

**Issue by hadoop73** [salman-h-khan/ZSD_Release#3]
Hi，When I run detect.py ,some errors occurs,` ModuleNotFoundError: No module named 'keras_frcnn.config\r'` , I use python=3.6 the package pickle is a standard part ，can't upgraded，SO how to generate the pick file config.pickle myself，thx

**Comment by michael20at** [comment]
I had the same problem, but found a solution!

The pickle file is already included (in the model folder), but it was saved as text and not in binary, the "\r" at the end is the problem! If you open the pickle file in an editor like notepad++ (showing non-printing characters) you will see a **cr lf** after every line. 

Just **replace (extended options) \r\n with \n** for the whole file and it should work!
