### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by noweshed-akram** [salman-h-khan/ZSD_Release#4]
when I run detect.py got this error
ValueError: Shape must be rank 1 but is rank 0 for 'bn_conv1/Reshape_4' (op: 'Reshape') with input shapes: [1,1,1,64], [].
will you kindly suggest me how i can fix it?

**Comment by AditAg** [comment]
Getting the same error. Has anyone found a solution?

**Comment by EmmanouelP** [comment]
Ok so in my case i had to downgrade my version of keras to the specific version mentioned in this repo.
Just uninstall your keras version with : pip uninstall keras, and install new version : pip install -I keras==2.0.8. If you stumble on new error concerning numpy issues just uninstall and re install numpy accordingly.
