### ISSUE TITLE
Can you share the detail about W2?

### ISSUE THREAD

**Issue by Bigwode** [salman-h-khan/ZSD_Release#5]
When I know the word, I can get it's word embedding vector, but when I know it's vector, I have no idea how to get it's words. W2 is word embedding vector.T or not? 
I can't find in the reference code, where calculate the cosine similiarity as the paper.

**Comment by shafin5** [comment]
Yes, W2 is the word vector embedding. The exact vectors are in the columns of ImageNet2017/word_w2v.txt with the class order written in ImageNet2017/cls_names.txt. Using those files, you can find each vector and its corresponding class name.

For cosine similarity, please check line no. 218 of detect.py:
P_cls[0,:,:] = P_cls[0,:,:] / np.multiply(a, b)
Here, P_cls has all projection values (output of the network at last layer) and 'a' and 'b' are the norms of visual vector and word vectors respectively. You can find that 'a' is calculated from 'model_classifier_Mylayer_output' which is an output of an intermediate layer of the network containing the visual feature.
