### ISSUE TITLE
Can you share the train code？

### ISSUE THREAD

**Issue by xisi789** [salman-h-khan/ZSD_Release#6]
Your work is very good!  Would you like to share the training codes. I want to test it on my dataset.

**Comment by salman-h-khan** [comment]
We have released the training code for our latest model. Check out: https://github.com/salman-h-khan/PL-ZSD_Release

**Comment by longyuz0426** [comment]
> Your work is very good! Would you like to share the training codes. I want to test it on my dataset.
Hi, did you try to use the training codes?
